#!/usr/bin/env bash
# bedrock-common.sh — shared helpers for Claude Code + AWS Bedrock in Workbench runtime.
# Sourced by bedrock-runtime-startup.sh. Do not execute directly.
#
# Authentication (pick one):
#   Auto-refresh (recommended): AWS_ACCESS_KEY_ID + AWS_SECRET_ACCESS_KEY (+ AWS_SESSION_TOKEN)
#     → claude-sync-config mints a short-term Bedrock bearer token (up to 12 hours).
#   Manual bearer token: AWS_BEARER_TOKEN_BEDROCK from the Bedrock console (up to 12 hours).
#
# Required for all modes:
#   BEDROCK_MODEL — Bedrock model id (e.g. us.anthropic.claude-sonnet-4-6)
#   AWS_REGION    — Bedrock region (falls back to AWS_DEFAULT_REGION)
#
# Optional:
#   BEDROCK_LITELLM_PORT — local LiteLLM proxy port (default: 4000)

: "${BEDROCK_HOME:?BEDROCK_HOME must be set before sourcing bedrock-common.sh}"

LITELLM_CONFIG="${BEDROCK_LITELLM_CONFIG:-${BEDROCK_HOME}/litellm-config.yaml}"
LITELLM_PID_FILE="${BEDROCK_LITELLM_PID_FILE:-${BEDROCK_HOME}/litellm.pid}"
LITELLM_LOG="${BEDROCK_LITELLM_LOG:-${BEDROCK_HOME}/litellm.log}"
BEARER_TOKEN_HASH_FILE="${BEDROCK_HOME}/bearer-token.hash"
LITELLM_PORT="${BEDROCK_LITELLM_PORT:-4000}"
LITELLM_MASTER_KEY="${BEDROCK_LITELLM_MASTER_KEY:-sk-bedrock-local-proxy}"
PROXY_URL="http://127.0.0.1:${LITELLM_PORT}"

BEDROCK_MAX_OUTPUT_TOKENS="${BEDROCK_MAX_OUTPUT_TOKENS:-8192}"
BEDROCK_MAX_INPUT_TOKENS="${BEDROCK_MAX_INPUT_TOKENS:-192000}"

CLAUDE_OPUS_ALIAS="${BEDROCK_CLAUDE_OPUS_ALIAS:-claude-opus-4-6}"
CLAUDE_SONNET_ALIAS="${BEDROCK_CLAUDE_SONNET_ALIAS:-claude-sonnet-4-6}"
CLAUDE_HAIKU_ALIAS="${BEDROCK_CLAUDE_HAIKU_ALIAS:-claude-haiku-4-5-20251001}"

bedrock_log() { printf '%s\n' "$*" >&2; }
bedrock_die() { bedrock_log "ERROR: $*"; return 1; }

bedrock_have_cmd() { command -v "$1" >/dev/null 2>&1; }

bedrock_aws_region() {
    printf '%s' "${AWS_REGION:-${AWS_DEFAULT_REGION:-}}"
}

bedrock_has_base_creds() {
    [[ -n "${AWS_ACCESS_KEY_ID:-}" && -n "${AWS_SECRET_ACCESS_KEY:-}" ]]
}

bedrock_has_bearer_token() {
    [[ -n "${AWS_BEARER_TOKEN_BEDROCK:-}" ]]
}

bedrock_auth_mode() {
    if bedrock_has_bearer_token; then
        printf 'bearer'
    elif bedrock_has_base_creds; then
        printf 'sigv4'
    else
        printf 'none'
    fi
}

bedrock_env_ready() {
    [[ -n "${BEDROCK_MODEL:-}" && -n "$(bedrock_aws_region)" ]] \
        && { bedrock_has_bearer_token || bedrock_has_base_creds; }
}

bedrock_litellm_model_id() {
    local model="${1:-${BEDROCK_MODEL}}"
    case "$model" in
        bedrock/*) printf '%s' "$model" ;;
        *) printf 'bedrock/invoke/%s' "$model" ;;
    esac
}

bedrock_venv_python() {
    local py="${BEDROCK_VENV_BIN:-/opt/bedrock-claude/venv/bin}/python"
    [ -x "$py" ] || { bedrock_die "Python venv not found at ${py}"; return 1; }
    printf '%s' "$py"
}

bedrock_litellm_bin() {
    local bin="${BEDROCK_VENV_BIN:-/opt/bedrock-claude/venv/bin}/litellm"
    [ -x "$bin" ] || { bedrock_die "LiteLLM not installed at ${bin}"; return 1; }
    printf '%s' "$bin"
}

bedrock_bearer_token_hash() {
    if ! bedrock_has_bearer_token; then
        return 0
    fi
    if bedrock_have_cmd shasum; then
        printf '%s' "$AWS_BEARER_TOKEN_BEDROCK" | shasum -a 256 | awk '{print $1}'
    else
        printf '%s' "$AWS_BEARER_TOKEN_BEDROCK" | wc -c | awk '{print $1}'
    fi
}

bedrock_refresh_bearer_token() {
    local py region token

    bedrock_has_base_creds || {
        bedrock_die "Base AWS credentials required to mint a bearer token."
        return 1
    }

    region="$(bedrock_aws_region)"
    [[ -n "$region" ]] || { bedrock_die "AWS_REGION required to mint bearer token."; return 1; }

    py="$(bedrock_venv_python)" || return 1
    export AWS_REGION="$region"
    export AWS_DEFAULT_REGION="$region"
    [[ -n "${AWS_SESSION_TOKEN:-}" ]] && export AWS_SESSION_TOKEN

    token="$("$py" - <<'PY'
from datetime import timedelta

from aws_bedrock_token_generator import provide_token

region = __import__("os").environ.get("AWS_REGION") or __import__("os").environ.get("AWS_DEFAULT_REGION")
print(provide_token(region=region, expiry=timedelta(hours=12)), end="")
PY
)" || {
        bedrock_die "Failed to mint Bedrock bearer token. Check AWS credentials and Bedrock permissions."
        return 1
    }

    [[ -n "$token" ]] || { bedrock_die "Minted bearer token was empty."; return 1; }
    export AWS_BEARER_TOKEN_BEDROCK="$token"
    return 0
}

bedrock_write_litellm_config() {
    local litellm_model region max_out max_in auth_mode="$1"
    litellm_model="$(bedrock_litellm_model_id)"
    region="$(bedrock_aws_region)"
    max_out="${BEDROCK_MAX_OUTPUT_TOKENS:-8192}"
    max_in="${BEDROCK_MAX_INPUT_TOKENS:-192000}"

    mkdir -p "$(dirname "$LITELLM_CONFIG")"

    if [[ "$auth_mode" == "bearer" ]]; then
        cat >"$LITELLM_CONFIG" <<YAML
# Generated by Claude Code + AWS Bedrock runtime (bearer token auth)
model_list:
  - model_name: ${CLAUDE_OPUS_ALIAS}
    litellm_params:
      model: ${litellm_model}
      api_key: os.environ/AWS_BEARER_TOKEN_BEDROCK
      aws_region_name: ${region}
      max_tokens: ${max_out}
    model_info:
      max_tokens: 200000
      max_input_tokens: ${max_in}
      max_output_tokens: ${max_out}
  - model_name: ${CLAUDE_SONNET_ALIAS}
    litellm_params:
      model: ${litellm_model}
      api_key: os.environ/AWS_BEARER_TOKEN_BEDROCK
      aws_region_name: ${region}
      max_tokens: ${max_out}
    model_info:
      max_tokens: 200000
      max_input_tokens: ${max_in}
      max_output_tokens: ${max_out}
  - model_name: ${CLAUDE_HAIKU_ALIAS}
    litellm_params:
      model: ${litellm_model}
      api_key: os.environ/AWS_BEARER_TOKEN_BEDROCK
      aws_region_name: ${region}
      max_tokens: ${max_out}
    model_info:
      max_tokens: 200000
      max_input_tokens: ${max_in}
      max_output_tokens: ${max_out}

litellm_settings:
  master_key: ${LITELLM_MASTER_KEY}
  drop_params: true
  modify_params: true
  request_timeout: 600
YAML
        return 0
    fi

    local session_token_block=""
    if [[ -n "${AWS_SESSION_TOKEN:-}" ]]; then
        session_token_block=$'      aws_session_token: os.environ/AWS_SESSION_TOKEN\n'
    fi

    cat >"$LITELLM_CONFIG" <<YAML
# Generated by Claude Code + AWS Bedrock runtime (SigV4 auth)
model_list:
  - model_name: ${CLAUDE_OPUS_ALIAS}
    litellm_params:
      model: ${litellm_model}
      aws_access_key_id: os.environ/AWS_ACCESS_KEY_ID
      aws_secret_access_key: os.environ/AWS_SECRET_ACCESS_KEY
${session_token_block}      aws_region_name: ${region}
      max_tokens: ${max_out}
    model_info:
      max_tokens: 200000
      max_input_tokens: ${max_in}
      max_output_tokens: ${max_out}
  - model_name: ${CLAUDE_SONNET_ALIAS}
    litellm_params:
      model: ${litellm_model}
      aws_access_key_id: os.environ/AWS_ACCESS_KEY_ID
      aws_secret_access_key: os.environ/AWS_SECRET_ACCESS_KEY
${session_token_block}      aws_region_name: ${region}
      max_tokens: ${max_out}
    model_info:
      max_tokens: 200000
      max_input_tokens: ${max_in}
      max_output_tokens: ${max_out}
  - model_name: ${CLAUDE_HAIKU_ALIAS}
    litellm_params:
      model: ${litellm_model}
      aws_access_key_id: os.environ/AWS_ACCESS_KEY_ID
      aws_secret_access_key: os.environ/AWS_SECRET_ACCESS_KEY
${session_token_block}      aws_region_name: ${region}
      max_tokens: ${max_out}
    model_info:
      max_tokens: 200000
      max_input_tokens: ${max_in}
      max_output_tokens: ${max_out}

litellm_settings:
  master_key: ${LITELLM_MASTER_KEY}
  drop_params: true
  modify_params: true
  request_timeout: 600
YAML
}

bedrock_proxy_health_ok() {
    curl -sf --connect-timeout 2 --max-time 5 \
        -H "Authorization: Bearer ${LITELLM_MASTER_KEY}" \
        "${PROXY_URL}/health/liveliness" >/dev/null 2>&1 \
        || curl -sf --connect-timeout 2 --max-time 5 "${PROXY_URL}/health" >/dev/null 2>&1
}

bedrock_stop_proxy() {
    if [ -f "$LITELLM_PID_FILE" ]; then
        local pid
        pid="$(cat "$LITELLM_PID_FILE" 2>/dev/null || true)"
        if [ -n "$pid" ] && kill -0 "$pid" 2>/dev/null; then
            kill "$pid" 2>/dev/null || true
            wait "$pid" 2>/dev/null || true
        fi
        rm -f "$LITELLM_PID_FILE"
    fi
}

bedrock_start_litellm_proxy() {
    local litellm_bin new_hash="" old_hash="" token_hash="" old_token_hash="" auth_mode
    bedrock_env_ready || {
        bedrock_die "Bedrock env not ready — set BEDROCK_MODEL, AWS_REGION, and credentials."
        return 1
    }

    auth_mode="$(bedrock_auth_mode)"
    litellm_bin="$(bedrock_litellm_bin)" || return 1
    bedrock_write_litellm_config "$auth_mode"

    if bedrock_have_cmd shasum; then
        new_hash="$(shasum -a 256 "$LITELLM_CONFIG" | awk '{print $1}')"
        old_hash="$(cat "${LITELLM_CONFIG}.hash" 2>/dev/null || true)"
    fi

    if [[ "$auth_mode" == "bearer" ]]; then
        token_hash="$(bedrock_bearer_token_hash)"
        old_token_hash="$(cat "$BEARER_TOKEN_HASH_FILE" 2>/dev/null || true)"
    fi

    if bedrock_proxy_health_ok \
        && [ -n "$new_hash" ] && [ "$new_hash" = "$old_hash" ] \
        && { [[ "$auth_mode" != "bearer" ]] || [[ -z "$token_hash" || "$token_hash" = "$old_token_hash" ]]; }; then
        return 0
    fi

    bedrock_stop_proxy
    region="$(bedrock_aws_region)"
    export AWS_REGION="$region"
    export AWS_DEFAULT_REGION="$region"
    : >"$LITELLM_LOG"

    if [[ "$auth_mode" == "bearer" ]]; then
        env AWS_REGION="$region" AWS_DEFAULT_REGION="$region" \
            AWS_BEARER_TOKEN_BEDROCK="$AWS_BEARER_TOKEN_BEDROCK" \
            "$litellm_bin" --config "$LITELLM_CONFIG" --host 127.0.0.1 --port "$LITELLM_PORT" \
            >>"$LITELLM_LOG" 2>&1 &
    else
        if [[ -n "${AWS_SESSION_TOKEN:-}" ]]; then
            env AWS_REGION="$region" AWS_DEFAULT_REGION="$region" \
                AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID" \
                AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY" \
                AWS_SESSION_TOKEN="$AWS_SESSION_TOKEN" \
                "$litellm_bin" --config "$LITELLM_CONFIG" --host 127.0.0.1 --port "$LITELLM_PORT" \
                >>"$LITELLM_LOG" 2>&1 &
        else
            env AWS_REGION="$region" AWS_DEFAULT_REGION="$region" \
                AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID" \
                AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY" \
                "$litellm_bin" --config "$LITELLM_CONFIG" --host 127.0.0.1 --port "$LITELLM_PORT" \
                >>"$LITELLM_LOG" 2>&1 &
        fi
    fi
    local pid=$!
    echo "$pid" >"$LITELLM_PID_FILE"

    local i
    for i in $(seq 1 30); do
        if bedrock_proxy_health_ok; then
            [ -n "$new_hash" ] && printf '%s' "$new_hash" >"${LITELLM_CONFIG}.hash"
            [[ -n "$token_hash" ]] && printf '%s' "$token_hash" >"$BEARER_TOKEN_HASH_FILE"
            return 0
        fi
        if ! kill -0 "$pid" 2>/dev/null; then
            bedrock_log "LiteLLM failed to start. Last log lines:"
            tail -20 "$LITELLM_LOG" >&2 || true
            bedrock_die "LiteLLM proxy exited unexpectedly." || return 1
        fi
        sleep 0.5
    done
    bedrock_die "LiteLLM proxy did not become healthy within 15s. See ${LITELLM_LOG}" || return 1
}

bedrock_write_claude_settings() {
    mkdir -p "$HOME/.claude"
    umask 077

    cat >"$HOME/.claude.json" <<EOF
{
  "hasCompletedOnboarding": true,
  "primaryApiKey": "${LITELLM_MASTER_KEY}"
}
EOF

    cat >"$HOME/.claude/settings.json" <<EOF
{
  "promptSuggestionEnabled": false,
  "model": "${CLAUDE_SONNET_ALIAS}",
  "env": {
    "ANTHROPIC_BASE_URL": "${PROXY_URL}",
    "ANTHROPIC_DEFAULT_OPUS_MODEL": "${CLAUDE_SONNET_ALIAS}",
    "ANTHROPIC_DEFAULT_SONNET_MODEL": "${CLAUDE_SONNET_ALIAS}",
    "ANTHROPIC_DEFAULT_HAIKU_MODEL": "${CLAUDE_HAIKU_ALIAS}",
    "CLAUDE_CODE_ENABLE_GATEWAY_MODEL_DISCOVERY": "1",
    "CLAUDE_CODE_DISABLE_1M_CONTEXT": "1",
    "CLAUDE_CODE_DISABLE_EXPERIMENTAL_BETAS": "1",
    "CLAUDE_CODE_MAX_OUTPUT_TOKENS": "${BEDROCK_MAX_OUTPUT_TOKENS:-8192}",
    "CLAUDE_CODE_ATTRIBUTION_HEADER": "0",
    "CLAUDE_CODE_ENABLE_TELEMETRY": "0",
    "CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC": "1"
  },
  "attribution": { "commit": "", "pr": "" }
}
EOF
}

bedrock_export_claude_env() {
    export ANTHROPIC_BASE_URL="$PROXY_URL"
    export ANTHROPIC_API_KEY="$LITELLM_MASTER_KEY"
    unset ANTHROPIC_AUTH_TOKEN
    export ANTHROPIC_DEFAULT_OPUS_MODEL="$CLAUDE_SONNET_ALIAS"
    export ANTHROPIC_DEFAULT_SONNET_MODEL="$CLAUDE_SONNET_ALIAS"
    export ANTHROPIC_DEFAULT_HAIKU_MODEL="$CLAUDE_HAIKU_ALIAS"
    export CLAUDE_CODE_ENABLE_GATEWAY_MODEL_DISCOVERY="${CLAUDE_CODE_ENABLE_GATEWAY_MODEL_DISCOVERY:-1}"
    export CLAUDE_CODE_DISABLE_1M_CONTEXT="${CLAUDE_CODE_DISABLE_1M_CONTEXT:-1}"
    export CLAUDE_CODE_DISABLE_EXPERIMENTAL_BETAS="${CLAUDE_CODE_DISABLE_EXPERIMENTAL_BETAS:-1}"
    export CLAUDE_CODE_MAX_OUTPUT_TOKENS="${BEDROCK_MAX_OUTPUT_TOKENS:-8192}"
}

bedrock_sync_config() {
    local verbose="${1:-0}" litellm_model region auth_mode

    if ! bedrock_env_ready; then
        bedrock_log "claude-sync-config: set BEDROCK_MODEL and AWS_REGION, then either:"
        bedrock_log "  • AWS_ACCESS_KEY_ID + AWS_SECRET_ACCESS_KEY (auto-mints 12h bearer token), or"
        bedrock_log "  • AWS_BEARER_TOKEN_BEDROCK (paste from Bedrock console API keys page)"
        return 1
    fi

    if bedrock_has_base_creds; then
        bedrock_refresh_bearer_token || return 1
    elif ! bedrock_has_bearer_token; then
        bedrock_die "No usable Bedrock credentials found." || return 1
    fi

    litellm_model="$(bedrock_litellm_model_id)"
    region="$(bedrock_aws_region)"
    auth_mode="$(bedrock_auth_mode)"

    bedrock_write_claude_settings
    bedrock_start_litellm_proxy || return 1
    bedrock_export_claude_env

    if [[ "$verbose" == "1" ]]; then
        bedrock_log "LiteLLM proxy: ${PROXY_URL} → ${litellm_model} (${region}, ${auth_mode})"
        bedrock_log "Model: ${BEDROCK_MODEL}"
        bedrock_log "Auth: short-term Bedrock bearer token (up to 12 hours)"
        bedrock_log "Output cap: ${BEDROCK_MAX_OUTPUT_TOKENS:-8192} tokens"
        bedrock_log "Token expires? Re-run: claude-sync-config"
        bedrock_log "Generate token: https://console.aws.amazon.com/bedrock/home#/api-keys"
        bedrock_log "Ready: claude"
    fi
}

bedrock_launch_claude() {
    bedrock_have_cmd claude || { bedrock_die "Claude Code CLI not installed."; return 127; }
    bedrock_sync_config 0 || return 1

    if [ $# -gt 0 ]; then
        command claude "$@"
    else
        command claude
    fi
}
